### ISSUE TITLE
Make a distinction between different data processing codes/queries

### ISSUE THREAD

**Issue by CherineJ** [LTER-LIFE/VeluweProtoDT#17]
There are different types of data processing codes or queries. Some are essential to convert primary data to usable input for further analyses (e.g., interpreting bud burst dates per tree per year from primary bud burst data), whilst others are non-essential (e.g., summary statistics).

**Comment by StefanVriend** [comment]
## Decision: using the idea of layers to differentiate codes/queries
### Description
Using layers to describe the steps in the workflow, the essential codes can be considered a necessary data processing step (i.e., secondary layer), whereas summary queries or analytical codes are both a tertiary layer.

Example workflow 1:

1. **Primary data**: bud burst data
2. **Data processing**: bud burst dates per tree per year
3. **Analytical**: climate window analysis

Example workflow 2:

1. **Primary data**: bud burst data
2. **Data processing**: bud burst dates per tree per year
3. **Analytical**: average bud burst date per year
