### ISSUE TITLE
Write script for visualising climwin outputs

### ISSUE THREAD

**Issue by StefanVriend** [LTER-LIFE/VeluweProtoDT#23]
Write scripts to visualise the model outputs of #27.

**Comment by StefanVriend** [comment]
Possible visualisations:

- climwin heat map (AIC)
- climwin's predicted values vs observed values for bud burst dates
- relationship between temperature in identified climate window and bud burst dates

**Comment by CherineJ** [comment]
We decided to create the climwin heat map of the first window and a plot of the relation between temperature in the best window and bud burst dates for both oak species to illustrate the outcomes of our analysis.

**Comment by StefanVriend** [comment]
Yet to update: colour scheme 👯 🥳
