### ISSUE TITLE
Write script for running climate window analysis (climwin)

### ISSUE THREAD

**Issue by StefanVriend** [LTER-LIFE/VeluweProtoDT#27]
Write script to run a {[climwin](https://github.com/LiamDBailey/climwin)} model (cq. [Bailey & van de Pol 2016](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0167980)) using the bud burst and temperature data.

{climwin} allows users to run two types of analysis:
- _relative_: window is number of days before each biological record
- _absolute_: window is number of days before a set point in time (i.e., reference day)

We only explore the _absolute_ analysis.

**Comment by StefanVriend** [comment]
{climwin} has elaborate documentation but sometimes the error messages are rather opaque.

```
Error: You do not have enough climate data to search 183 days before 1988-04-28. Please adjust the value of range or add additional climate data. 
```
This error message seems incorrect. In this case, we run a model of the 'absolute' type with a reference date of 31st of May. However, the message suggests that the analysis was of the 'relative' type (as it refers to the earliest biological date and not the reference date).

```
Error: Climate data should not contain NA values: 3828 NA value(s) found. Please add missing climate data or set cmissing to `method1` or `method2`. See object 'missing' for all missing climate data.
```
This error message is rather opaque. It suggests that there are missing values in the climate/temperature data. When looking at the `missing` R object, it produces dates that we did not include in our climate data on purpose (i.e., we were only interested in finding a window between 1 December and 31 May, but `missing` included dates in June, July, etc.). However, there actually _were_ missing values in our selected period (as a result of the EDR API failing sometimes, see #2 or #25), and that is what caused this error.

**Comment by CherineJ** [comment]
With the complete temperature data, the reference day of the 31 of May and a possible range of windows from 181 to 0 days before the reference day, all abovementioned errors are solved and the _climwin_ analysis runs.
