### ISSUE TITLE
Match data of Open API and EDR API of KNMI

### ISSUE THREAD

**Issue by CherineJ** [LTER-LIFE/VeluweProtoDT#4]
The two APIs of the KNMI provide data in different coordinate systems ([EPSG:28992](https://epsg.io/28992) & [EPSG:4326](https://epsg.io/4326)). When trying to transform coordinates from one system to the other, they do not match but are slightly shifted. As both APIs query the same underlying data set, temperature values should have the exact same coordinates after transformation. For the decision which API to use (see #2), the differences in the coordinates need to be understood.

**Comment by StefanVriend** [comment]
In the background, the EDR API uses a WCS call to [Adaguc](https://adaguc.knmi.nl/) (an open source WMS/WCS server). The transformations between coordinate systems happen within Adaguc. Paul van Schayk, our contact person at the KNMI Open data team, has forwarded our issues/question to colleagues (unclear whether they are internal or at Adaguc) on 21/11/2023.

**Comment by CherineJ** [comment]
## Explanation & Takeaway
Paul van Schayk got back to us (December 11, 2023) and explained that the temperature values in the netCDF files (i.e., Open API) belong to the midpoints of the grid cells, while the transformation in Adaguc (i.e., EDR API) shifts the temperature values to the corner points of the grid. There is therefore, as we already assumed, a slight shift in the temperature grid.
