### ISSUE TITLE
Map DwC terms to the bud burst data

### ISSUE THREAD

**Issue by CherineJ** [LTER-LIFE/VeluweProtoDT#9]
The relational Access data base, in which the raw bud burst data is stored, consists of several linked tables. The Darwin Core archive requires separate files (core file and extensions), each having a defined set of possible Darwin Core terms. The Darwin Core terms need to be matched to the column names of  bud burst data. This is however not always straightforward, as some DwC terms do not have equivalents in the data and columns of several data files of the bud burst data need to be linked and columns combined to create one of the DwC-A files.

**Comment by StefanVriend** [comment]
Duplicate of #14.
